# Calibration results details:
# Bag: 2018-12-13-12-31-33-IMU_Intrinsics.mat
# Details: ~4 hour bag of IMU sitting on a table, no disturbances. Not on robot.
# Data Processed: 2018 12 14

#Accelerometers
accelerometer_noise_density: 0.05727787   #Noise density (continuous-time)
accelerometer_random_walk:   0.00204802   #Bias random walk

#Gyroscopes
gyroscope_noise_density:     0.02214779   #Noise density (continuous-time)
gyroscope_random_walk:       0.00077558   #Bias random walk

rostopic:                    /imu/data  #the IMU ROS topic
update_rate:                 20.0       #Hz (for discretization of the values above)
